fix: dotcore update and force run mode

diff --git a/bin/dotcore b/bin/dotcore
--- a/bin/dotcore
+++ b/bin/dotcore
@@ -4,7 +4,34 @@ set -e
 
 $(shim) && cd ${DOTCORE_DIR} && . bin/i.sh
 
-log:: "updating dotfiles"
+command_install() {
+  log:: "installing dotfiles"
+  dotcore-pull
+  dotcore-apt
+  dotcore-stow
+}
 
-dotcore-apt
-dotcore-stow
+while getopts "F" opt; do
+  case "$opt" in
+  F)
+    FORCE_ALL=1
+    ;;
+  esac
+done
+
+shift $((OPTIND - 1))
+[ "${1:-}" == "--" ] && shift
+
+if [[ -n "$FORCE_ALL" ]]; then
+  for f in ${DOTCORE_DIR}/bin/dotcore-*; do
+    should-run -c ${f##*/}
+  done
+fi
+
+COMMAND=${1:-install}
+command_${COMMAND} $@
+if [ $? = 127 ]; then
+  echo "'$COMMAND_NAME' is not a known command or has errors." >&2
+  usage
+  exit 1
+fi
